#PYTHON PROGRAM TO CALCULATE SIMPLE INTEREST AND COMPOUND INTEREST
import math
P=int(input("ENTER THE PRINCIPAL AMOUNT"))
N=int(input("ENTER NO OF YEARS "))
R=int(input("ENTER THE RATE OF INTEREST"))
SI=(P*N*R)/100
C=(1+(R/100))**N
A=P*C
CI=A-P
print("THE SIMPLE INTEREST IS:",SI)
print("THE COMPOUND INTEREST IS:",CI)
